-- 不動産管理システムDB
-- DB名：realestate
-- ユーザー名：realestate_login
-- パスワード：bsadmin
-- テーブル：CMPN, RPPS, LAND, RSDC, ROOM, TNNT, UDPY, DEPY, ADIT, ADEB, ADEH, DDCT

-- ロール追加（初回DB構築時のみ）
-- alter role realestate_login with password 'bsadmin';

-- DB新規作成（DB構築時のみ）
-- create database "realestate" owner realestate_login encoding 'UTF8';

-- 旧テーブル削除
DROP TABLE CMPN;
DROP TABLE RPPS;
DROP TABLE LAND;
DROP TABLE RSDC;
DROP TABLE ROOM;
DROP TABLE TNNT;
DROP TABLE UDPY;
DROP TABLE DEPY;
DROP TABLE ADIT;
DROP TABLE ADEB;
DROP TABLE ADEH;
DROP TABLE DDCT;

-- CMPNテーブル
CREATE TABLE CMPN(
    CMPNID VARCHAR(7)    unique primary key,
    CMPNNM VARCHAR(100)  not null,
    CMPNNF VARCHAR(100)  not null,
    RPSTNM VARCHAR(100)  not null,
    BRNCNM VARCHAR(100)  not null,
    USERNM VARCHAR(32)   not null unique,
    PASSWD VARCHAR(32)   not null,
    ZIPCOD VARCHAR(8)    not null,
    STATNM VARCHAR(100)  not null,
    CITYNM VARCHAR(100)  not null,
    STRNO1 VARCHAR(100)  not null,
    STRNO2 VARCHAR(100)  ,
    NUMBER VARCHAR(13)   not null,
    FAXNUM VARCHAR(12)   ,
    BANKNM VARCHAR(100)  ,
    BANKBR VARCHAR(100)  ,
    ACNTTY VARCHAR(100)  ,
    ACNTNU VARCHAR(7)    ,
    ACNTNM VARCHAR(100)  ,
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN CMPN.CMPNID IS '自社ID';
COMMENT ON COLUMN CMPN.CMPNNM IS '自社名';
COMMENT ON COLUMN CMPN.CMPNNF IS '自社名フリガナ';
COMMENT ON COLUMN CMPN.RPSTNM IS '代表者名';
COMMENT ON COLUMN CMPN.BRNCNM IS '本支店名';
COMMENT ON COLUMN CMPN.USERNM IS 'ユーザー名';
COMMENT ON COLUMN CMPN.PASSWD IS 'パスワード';
COMMENT ON COLUMN CMPN.ZIPCOD IS '郵便番号';
COMMENT ON COLUMN CMPN.STATNM IS '都道府県';
COMMENT ON COLUMN CMPN.CITYNM IS '市区町村';
COMMENT ON COLUMN CMPN.STRNO1 IS '番地1';
COMMENT ON COLUMN CMPN.STRNO2 IS '番地2';
COMMENT ON COLUMN CMPN.NUMBER IS '電話番号';
COMMENT ON COLUMN CMPN.FAXNUM IS 'FAX';
COMMENT ON COLUMN CMPN.BANKNM IS '銀行名';
COMMENT ON COLUMN CMPN.BANKBR IS '銀行支店名';
COMMENT ON COLUMN CMPN.ACNTTY IS '口座区分';
COMMENT ON COLUMN CMPN.ACNTNU IS '口座番号';
COMMENT ON COLUMN CMPN.ACNTNM IS '口座名義';
COMMENT ON COLUMN CMPN.COMMNT IS 'コメント';
COMMENT ON COLUMN CMPN.RGDTTM IS '登録日時';
COMMENT ON COLUMN CMPN.UDDTTM IS '更新日時';

-- RPPSテーブル
CREATE TABLE RPPS(
    RPPSID VARCHAR(15)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    RPPSNM VARCHAR(100)  not null,
    RPPSNF VARCHAR(100)  not null,
    PHONE1 VARCHAR(13)   not null,
    PHONE2 VARCHAR(13)   ,
    EMLADR VARCHAR(100)  not null,
    ACTVFG BOOLEAN       default 'true',
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN RPPS.RPPSID IS '担当者ID';
COMMENT ON COLUMN CMPN.CMPNID IS '自社ID';
COMMENT ON COLUMN RPPS.RPPSNM IS '担当者名';
COMMENT ON COLUMN RPPS.RPPSNF IS '担当者名フリガナ';
COMMENT ON COLUMN RPPS.PHONE1 IS '電話番号1';
COMMENT ON COLUMN RPPS.PHONE2 IS '電話番号2';
COMMENT ON COLUMN RPPS.EMLADR IS 'メールアドレス';
COMMENT ON COLUMN RPPS.ACTVFG IS '有効フラグ';
COMMENT ON COLUMN RPPS.COMMNT IS 'コメント';
COMMENT ON COLUMN RPPS.RGDTTM IS '登録日時';
COMMENT ON COLUMN RPPS.UDDTTM IS '更新日時';

-- LANDテーブル
CREATE TABLE LAND(
    LANDID VARCHAR(15)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    LANDNM VARCHAR(100)  not null,
    LANDNF VARCHAR(100)  not null,
    ZIPCOD VARCHAR(8)    not null,
    STATNM VARCHAR(100)  not null,
    CITYNM VARCHAR(100)  not null,
    STRNO1 VARCHAR(100)  not null,
    STRNO2 VARCHAR(100)  ,
    PHONE1 VARCHAR(13)   not null,
    PHONE2 VARCHAR(13)   ,
    EMLADR VARCHAR(100)  not null,
    BANKNM VARCHAR(100)  ,
    BANKBR VARCHAR(100)  ,
    ACNTTY VARCHAR(100)  ,
    ACNTNU VARCHAR(7)    ,
    ACNTNM VARCHAR(100)  ,
    ACTVFG BOOLEAN       default 'true',
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN LAND.LANDID IS '大家ID';
COMMENT ON COLUMN LAND.CMPNID IS '自社ID';
COMMENT ON COLUMN LAND.LANDNM IS '大家名';
COMMENT ON COLUMN LAND.LANDNF IS '大家名フリガナ';
COMMENT ON COLUMN LAND.ZIPCOD IS '郵便番号';
COMMENT ON COLUMN LAND.STATNM IS '都道府県';
COMMENT ON COLUMN LAND.CITYNM IS '市区町村';
COMMENT ON COLUMN LAND.STRNO1 IS '番地1';
COMMENT ON COLUMN LAND.STRNO2 IS '番地2';
COMMENT ON COLUMN LAND.PHONE1 IS '電話番号1';
COMMENT ON COLUMN LAND.PHONE2 IS '電話番号2';
COMMENT ON COLUMN LAND.EMLADR IS 'メールアドレス';
COMMENT ON COLUMN LAND.BANKNM IS '銀行名';
COMMENT ON COLUMN LAND.BANKBR IS '銀行支店名';
COMMENT ON COLUMN LAND.ACNTTY IS '口座区分';
COMMENT ON COLUMN LAND.ACNTNU IS '口座番号';
COMMENT ON COLUMN LAND.ACNTNM IS '口座名義';
COMMENT ON COLUMN LAND.ACTVFG IS '有効フラグ';
COMMENT ON COLUMN LAND.COMMNT IS 'コメント';
COMMENT ON COLUMN LAND.RGDTTM IS '登録日時';
COMMENT ON COLUMN LAND.UDDTTM IS '更新日時';

-- RSDCテーブル
CREATE TABLE RSDC(
    RSDCID VARCHAR(15)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    LANDID VARCHAR(15)   not null,
    RSDCNM VARCHAR(100)  not null unique,
    RSDCNF VARCHAR(100)  not null unique,
    ZIPCOD VARCHAR(8)    not null,
    STATNM VARCHAR(100)  not null,
    CITYNM VARCHAR(100)  not null,
    STRNO1 VARCHAR(100)  not null,
    RENTFE VARCHAR(10)   ,
    MNGFEE VARCHAR(10)   ,
    DEPSIT VARCHAR(10)   ,
    HNRRUM VARCHAR(10)   ,
    BRKRAG VARCHAR(10)   ,
    KEYFEE VARCHAR(10)   ,
    ACTVFG BOOLEAN       default 'true',
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN RSDC.RSDCID IS '物件ID';
COMMENT ON COLUMN RSDC.CMPNID IS '自社ID';
COMMENT ON COLUMN RSDC.LANDID IS '大家ID';
COMMENT ON COLUMN RSDC.RSDCNM IS '物件名';
COMMENT ON COLUMN RSDC.RSDCNF IS '物件名フリガナ';
COMMENT ON COLUMN RSDC.ZIPCOD IS '郵便番号';
COMMENT ON COLUMN RSDC.STATNM IS '都道府県';
COMMENT ON COLUMN RSDC.CITYNM IS '市区町村';
COMMENT ON COLUMN RSDC.STRNO1 IS '番地1';
COMMENT ON COLUMN RSDC.RENTFE IS '家賃';
COMMENT ON COLUMN RSDC.MNGFEE IS '共益費';
COMMENT ON COLUMN RSDC.DEPSIT IS '敷金';
COMMENT ON COLUMN RSDC.HNRRUM IS '礼金';
COMMENT ON COLUMN RSDC.BRKRAG IS '仲介料';
COMMENT ON COLUMN RSDC.KEYFEE IS '鍵代金';
COMMENT ON COLUMN RSDC.ACTVFG IS '有効フラグ';
COMMENT ON COLUMN RSDC.COMMNT IS 'コメント';
COMMENT ON COLUMN RSDC.RGDTTM IS '登録日時';
COMMENT ON COLUMN RSDC.UDDTTM IS '更新日時';

-- ROOMテーブル
CREATE TABLE ROOM(
    ROOMID VARCHAR(20)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    RSDCID VARCHAR(15)   not null,
    ROOMNU VARCHAR(10)   not null,
    CNTRCT BOOLEAN       default 'false',
    RENTFE VARCHAR(10)   not null,
    MNGFEE VARCHAR(10)   not null,
    DEPSIT VARCHAR(10)   not null,
    HNRRUM VARCHAR(10)   not null,
    BRKRAG VARCHAR(10)   not null,
    KEYFEE VARCHAR(10)   not null,
    ACTVFG BOOLEAN       default 'true',
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp,
    UNIQUE (RSDCID, ROOMNU)
);

COMMENT ON COLUMN ROOM.ROOMID IS '部屋ID';
COMMENT ON COLUMN ROOM.CMPNID IS '自社ID';
COMMENT ON COLUMN ROOM.RSDCID IS '物件ID';
COMMENT ON COLUMN ROOM.ROOMNU IS '部屋番号';
COMMENT ON COLUMN ROOM.CNTRCT IS '契約有無';
COMMENT ON COLUMN ROOM.RENTFE IS '家賃';
COMMENT ON COLUMN ROOM.MNGFEE IS '管理費';
COMMENT ON COLUMN ROOM.DEPSIT IS '敷金';
COMMENT ON COLUMN ROOM.HNRRUM IS '礼金';
COMMENT ON COLUMN ROOM.BRKRAG IS '仲介料';
COMMENT ON COLUMN ROOM.KEYFEE IS '鍵代金';
COMMENT ON COLUMN ROOM.ACTVFG IS '有効フラグ';
COMMENT ON COLUMN ROOM.COMMNT IS 'コメント';
COMMENT ON COLUMN ROOM.RGDTTM IS '登録日時';
COMMENT ON COLUMN ROOM.UDDTTM IS '更新日時';

-- TNNTテーブル
CREATE TABLE TNNT(
    TNNTID VARCHAR(15)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    RPPSID VARCHAR(15)   ,
    RSDCID VARCHAR(15)   ,
    ROOMID VARCHAR(20)   ,
    CONTDT VARCHAR(10)   ,
    TNNTNM VARCHAR(100)  not null,
    TNNTNF VARCHAR(100)  not null,
    ZIPCOD VARCHAR(8)    not null,
    STATNM VARCHAR(100)  not null,
    CITYNM VARCHAR(100)  not null,
    STRNO1 VARCHAR(100)  not null,
    STRNO2 VARCHAR(100)  ,
    PHONE1 VARCHAR(13)   not null,
    PHONE2 VARCHAR(13)   ,
    EMLADR VARCHAR(100)  ,
    BRTHDY VARCHAR(10)   ,
    BANKNM VARCHAR(100)  ,
    BANKBR VARCHAR(100)  ,
    ACNTTY VARCHAR(100)  ,
    ACNTNU VARCHAR(7)    ,
    ACNTNM VARCHAR(100)  ,
    WKPCNM VARCHAR(100)  ,
    WKPCNF VARCHAR(100)  ,
    WKPZIP VARCHAR(8)    ,
    WKPSTA VARCHAR(100)  ,
    WKPCIT VARCHAR(100)  ,
    WKPST1 VARCHAR(100)  ,
    WKPST2 VARCHAR(100)  ,
    ACTVFG BOOLEAN       default 'true',
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN TNNT.TNNTID IS '借主ID';
COMMENT ON COLUMN TNNT.CMPNID IS '自社ID';
COMMENT ON COLUMN TNNT.RPPSID IS '担当者ID';
COMMENT ON COLUMN TNNT.RSDCID IS '契約中の物件ID';
COMMENT ON COLUMN TNNT.ROOMID IS '契約中の部屋ID';
COMMENT ON COLUMN TNNT.CONTDT IS '契約日';
COMMENT ON COLUMN TNNT.TNNTNM IS '借主名';
COMMENT ON COLUMN TNNT.TNNTNF IS '借主名フリガナ';
COMMENT ON COLUMN TNNT.ZIPCOD IS '郵便番号';
COMMENT ON COLUMN TNNT.STATNM IS '都道府県';
COMMENT ON COLUMN TNNT.CITYNM IS '市区町村';
COMMENT ON COLUMN TNNT.STRNO1 IS '番地1';
COMMENT ON COLUMN TNNT.STRNO2 IS '番地2';
COMMENT ON COLUMN TNNT.PHONE1 IS '電話番号1';
COMMENT ON COLUMN TNNT.PHONE2 IS '電話番号2';
COMMENT ON COLUMN TNNT.EMLADR IS 'メールアドレス';
COMMENT ON COLUMN TNNT.BRTHDY IS '生年月日';
COMMENT ON COLUMN TNNT.BANKNM IS '銀行名';
COMMENT ON COLUMN TNNT.BANKBR IS '銀行支店名';
COMMENT ON COLUMN TNNT.ACNTTY IS '口座区分';
COMMENT ON COLUMN TNNT.ACNTNU IS '口座番号';
COMMENT ON COLUMN TNNT.ACNTNM IS '口座名義';
COMMENT ON COLUMN TNNT.WKPCNM IS '勤務先名';
COMMENT ON COLUMN TNNT.WKPCNF IS '勤務先名フリガナ';
COMMENT ON COLUMN TNNT.WKPZIP IS '勤務先郵便番号';
COMMENT ON COLUMN TNNT.WKPSTA IS '勤務先都道府県';
COMMENT ON COLUMN TNNT.WKPCIT IS '勤務先市区町村';
COMMENT ON COLUMN TNNT.WKPST1 IS '勤務先番地1';
COMMENT ON COLUMN TNNT.WKPST2 IS '勤務先番地2';
COMMENT ON COLUMN TNNT.ACTVFG IS '有効フラグ';
COMMENT ON COLUMN TNNT.COMMNT IS 'コメント';
COMMENT ON COLUMN TNNT.RGDTTM IS '登録日時';
COMMENT ON COLUMN TNNT.UDDTTM IS '更新日時';

-- UDPYテーブル
CREATE TABLE UDPY(
    PYMTNU VARCHAR(18)  unique primary key,
    CMPNID VARCHAR(7)   not null,
    PAYDAT VARCHAR(10)  not null,
    PAYENM VARCHAR(100) not null,
    RCVAMT VARCHAR(10)  not null,
    CMFRMD BOOLEAN      default 'false',
    RGDTTM TIMESTAMP(0) default current_timestamp
);

COMMENT ON COLUMN UDPY.PYMTNU IS '消込番号';
COMMENT ON COLUMN UDPY.CMPNID IS '自社ID';
COMMENT ON COLUMN UDPY.PAYDAT IS '支払い日';
COMMENT ON COLUMN UDPY.PAYENM IS '支払い者氏名';
COMMENT ON COLUMN UDPY.RCVAMT IS '入金額';
COMMENT ON COLUMN UDPY.CMFRMD IS '確定';
COMMENT ON COLUMN UDPY.RGDTTM IS '登録日時';

-- DEPYテーブル
CREATE TABLE DEPY(
    PYMTNU VARCHAR(18)  unique primary key,
    CMPNID VARCHAR(7)   not null,
    PAYDAT VARCHAR(10)  not null,
    TNNTID VARCHAR(15)  not null,
    RSDCID VARCHAR(15)  not null,
    ROOMID VARCHAR(20)  not null,
    PAYAMT VARCHAR(10)  not null,
    RCVAMT VARCHAR(10)  not null,
    BALANC VARCHAR(10)  not null,
    RGDTTM TIMESTAMP(0) default current_timestamp
);

COMMENT ON COLUMN DEPY.PYMTNU IS '消込番号';
COMMENT ON COLUMN DEPY.CMPNID IS '自社ID';
COMMENT ON COLUMN DEPY.PAYDAT IS '支払い日';
COMMENT ON COLUMN DEPY.TNNTID IS '借主ID';
COMMENT ON COLUMN DEPY.RSDCID IS '契約中の物件ID';
COMMENT ON COLUMN DEPY.ROOMID IS '契約中の部屋ID';
COMMENT ON COLUMN DEPY.PAYAMT IS '支払い額';
COMMENT ON COLUMN DEPY.RCVAMT IS '入金額';
COMMENT ON COLUMN DEPY.BALANC IS '差額';
COMMENT ON COLUMN DEPY.RGDTTM IS '登録日時';

-- ADITテーブル
CREATE TABLE ADIT(
    ADITID VARCHAR(15)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    ITEMNM VARCHAR(100)  not null,
    ITEMID VARCHAR(100)  not null,
    MAXLNG VARCHAR(2)    ,
    SPCLNG VARCHAR(100)  ,
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp,
    UNIQUE (CMPNID, ITEMNM),
    UNIQUE (CMPNID, ITEMID)
);

COMMENT ON COLUMN ADIT.ADITID IS '追加項目ID';
COMMENT ON COLUMN ADIT.CMPNID IS '自社ID';
COMMENT ON COLUMN ADIT.ITEMNM IS '追加項目表示名';
COMMENT ON COLUMN ADIT.ITEMID IS '追加項目ID名';
COMMENT ON COLUMN ADIT.MAXLNG IS '最大桁数';
COMMENT ON COLUMN ADIT.SPCLNG IS '桁数指定';
COMMENT ON COLUMN ADIT.COMMNT IS 'コメント';
COMMENT ON COLUMN ADIT.RGDTTM IS '登録日時';
COMMENT ON COLUMN ADIT.UDDTTM IS '更新日時';

-- ADEBテーブル
CREATE TABLE ADEB(
    ADEBID VARCHAR(18)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    RSDCID VARCHAR(15)   not null,
    ADITID VARCHAR(15)   not null,
    ADEBVL VARCHAR(100)  not null,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN ADEB.ADEBID IS '追加費用ID';
COMMENT ON COLUMN ADEB.CMPNID IS '自社ID';
COMMENT ON COLUMN ADEB.RSDCID IS '物件ID';
COMMENT ON COLUMN ADEB.ADITID IS '追加項目ID';
COMMENT ON COLUMN ADEB.ADEBVL IS '追加費用';
COMMENT ON COLUMN ADEB.RGDTTM IS '登録日時';
COMMENT ON COLUMN ADEB.UDDTTM IS '更新日時';

-- ADEHテーブル
CREATE TABLE ADEH(
    ADEHID VARCHAR(18)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    ROOMID VARCHAR(20)   not null,
    ADITID VARCHAR(15)   not null,
    ADEHVL VARCHAR(100)  not null,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN ADEH.ADEHID IS '追加費用ID';
COMMENT ON COLUMN ADEH.CMPNID IS '自社ID';
COMMENT ON COLUMN ADEH.ROOMID IS '部屋ID';
COMMENT ON COLUMN ADEH.ADITID IS '追加項目ID';
COMMENT ON COLUMN ADEH.ADEHVL IS '追加費用';
COMMENT ON COLUMN ADEH.RGDTTM IS '登録日時';
COMMENT ON COLUMN ADEH.UDDTTM IS '更新日時';

-- DDCTテーブル
CREATE TABLE DDCT(
    DDCTID VARCHAR(15)   unique primary key,
    CMPNID VARCHAR(7)    not null,
    DDCTNM VARCHAR(100)  not null,
    DDITID VARCHAR(100)  not null,
    MAXLNG VARCHAR(2)    ,
    SPCLNG VARCHAR(100)  ,
    COMMNT VARCHAR(8000) ,
    RGDTTM TIMESTAMP(0)  default current_timestamp,
    UDDTTM TIMESTAMP(0)  default current_timestamp
);

COMMENT ON COLUMN DDCT.DDCTID IS '控除項目ID';
COMMENT ON COLUMN DDCT.CMPNID IS '自社ID';
COMMENT ON COLUMN DDCT.DDCTNM IS '控除項目表示名';
COMMENT ON COLUMN DDCT.DDITID IS '控除項目ID名';
COMMENT ON COLUMN DDCT.MAXLNG IS '最大桁数';
COMMENT ON COLUMN DDCT.SPCLNG IS '桁数指定';
COMMENT ON COLUMN DDCT.COMMNT IS 'コメント';
COMMENT ON COLUMN DDCT.RGDTTM IS '登録日時';
COMMENT ON COLUMN DDCT.UDDTTM IS '更新日時';
